branch-defaults:
  task-10:
    environment: task-10v1
    group_suffix: null
global:
  application_name: romanneudakh-bff-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
